### ISSUE TITLE
A small bug in `config.physical` to load data  

### ISSUE THREAD

**Issue by sherrylixuecheng** [mdsunivie/deeperwin#11]
Hello everyone,

Thank you so much for your previous reply and update. I would like to report another issue.

When I tried to run [config_bm_hfcoeff.yml](https://github.com/mdsunivie/deeperwin/blob/master/sample_configs/pre_training_basemodel/config_bm_hfcoeff.yml) by `deeperwin run config_bm_hfcoeff.yml`, I received the following error flags. 
`
Traceback (most recent call last):
  File "/anaconda/envs/deeperwin/bin/deeperwin", line 33, in <module>
    sys.exit(load_entry_point('deeperwin', 'console_scripts', 'deeperwin')())
  File "/home/t-shcheng/work/deeperwin/src/deeperwin/cli.py", line 16, in main
    process_single_molecule(args.config_file)
  File "/home/t-shcheng/work/deeperwin/src/deeperwin/process_molecule.py", line 99, in process_single_molecule
    tuple(config.physical.Z))
AttributeError: 'str' object has no attribute 'Z'
`

When I print out the `config.physical`, it give `TinyMol_CNO_rot_dist_train_18compounds_360geoms`, which is the name of the dataset not a geometry. Note that single molecule jobs run perfectly. I feel maybe we need to have a modified data loader for a dataset. 

I would really appreciate if anyone could take a look at this set of codes. Many thanks ahead for your help!

Best,
Sherry Cheng

**Comment by MScherbela** [comment]
Thanks for pointing out this issue!

**Short explanation**
The way, we typically use the code (which admittedly is not well documented) is not by calling `deeperwin run my_config.yml` directly, but by calling `deeperwin setup -i my_config.yml`.
This does several things:

1. It creates a new directory for the experiment
2. It optionally allows quick changing or sweeping of parameters using the `-p` flag, e.g. `deeperwin setup -i my_config.yml -p optimization.optimizer.learning_rate 0.1 0.2 0.4`
3. **It replaces geometry hashes or geometry datasets with their full configuration (i.e. R, Z, ...)**
4. It then calls `deeperwin run` on this expanded config-file (including the -p flags and the expanded geometries). Optionally this is also not run directly, but instead submitted as SLURM job

Our code thus currently expects that `deeperwin run` gets a full config-file as input, including a fully expanded `config.physical`. This is somewhat by design, so that it is always clear what exact system is being calculated, since this might not be immediately clear from the dataset-name, since the underlying geometries might in principle get lost or change.

**There are thus 2 options:**

- Quick: Use `deeperwin setup -i config_bm_hfcoeff.yml`, instead of `deeperwin run`, optionally enjoying the benefits of SLURM and the -p flags. If you want to use SLURM this might require minor adjustments in `src/deeperwin/run_tools/dispatch.py` to adjust the SLURM-template to your particular cluster.
- Alternative: Expand the geometry dataset also in `deeperwin run`, by basically porting the follwing 2 lines from `setup_calculations.py`, to `process_molecule.py`. I'd be happy to merge a pull request.

```python
        if isinstance(config_dict['physical'], (str, list)):
            config_dict['physical'] = dict(changes=expand_geometry_list(config_dict['physical']))
```

**Comment by sherrylixuecheng** [comment]
Thank you so much for your reply! Sorry for misunderstanding the running commands. I will try the ways you provided. Thank you again!
Best,
Sherry
