### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Augus1999** [mdsunivie/deeperwin#3]
When running `!deeperwin -f lih.yml` in Google Colab, an error occurred as
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/deeperwin/process_molecules_shared.py", line 227, in <module>
    log_psi_squared, mcmc, wfs, init_shared_params, optimize_epoch, opt_state, opt_get_params, opt_set_params = init_wfs(
  File "/usr/local/lib/python3.9/dist-packages/deeperwin/process_molecules_shared.py", line 61, in init_wfs
    new_shared_params, wf.unique_trainable_params = split_trainable_params(new_trainable_params,
  File "/usr/local/lib/python3.9/dist-packages/deeperwin/utils.py", line 363, in split_trainable_params
    for module in shared_modules:
TypeError: 'NoneType' object is not iterable
```
The file `lih.yml` is written the same as in document:
```yml
physical:
    name: LiH
    changes:
      - R: [[0,0,0],[3.0,0,0]]
        comment: "Equilibrium bond length"
      - R: [[0,0,0],[2.8,0,0]]
        comment: "Compressed molecule"
      - R: [[0,0,0],[3.2,0,0]]
        comment: "Stretched molecule"
optimization:
    shared_optimization:
        use: True
```

python version 3.9
jax==0.3.1
jaxlib==0.1.74+cuda11.cudnn805
deeperwin installed via `!pip install git+https://github.com/mdsunivie/deeperwin.git`

---
Can you give some hints about how to deal with this?

**Comment by Augus1999** [comment]
Hi, I think I find the reason.
My understanding is that if `optimization.shared_optimization.use=True`, the option `optimization.shared_optimization.shared_modules` must be filled.
If this is correct, can you add this to document?

**Comment by LeonGerBerlin** [comment]
Hi,

Yes, that is correct. Thank you for the hint. We will add it to the documentation and in the tutorial. 

We never thought about the case because in general when using shared optimization, you want to share part of the network weights as well to gain a speed-up during training. 

By the way feel free to contact us over mail (deeperwin.datascience@univie.ac.at) if you want to discuss further parts of the architecture or have any questions regarding it.
